# Site settings
title: Browserhacks
description: > # this means to ignore newlines until "baseurl:"
  Browserhacks is an extensive list of browser specific CSS and JavaScript hacks from all over the interwebs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://browserhacks.com" # the base hostname & protocol for your site
twitter_username: browserhacks

# Build settings
markdown: kramdown
sass:
  style: :compressed
  sass_dir: assets/scss
empty_array: []

exclude:
  - node_modules/
  - CNAME
  - Gruntfile.js
  - package.json
  - README.md
  - tasks/
